//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public Queue() { }

        public Queue(QueueType qType)
        {
            QueueType = ((char)qType).ToString();
            Status = (int)QueueStatus.Waiting;
            CreatedAt = DateTime.Now;
            UpdatedAt = CreatedAt;
        }

        private char queueType;

        public int QueueNo { get; set; }
        public string QueueType
        {
            get => queueType.ToString();
            set => queueType = (char)value[0];
        }
        public short Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<int> CounterNo { get; set; }
    }
}
